language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
services:
  - redis
  
# https://tea.xyz/what-is-this-file
---
version: 1.0.0
codeOwners:
  - '0xF9fD4579f66bf07C587F589149f5B348CCeB7578'
quorum: 1
